### ISSUE TITLE
ICorrelatableFrame / RequestAsync

### ISSUE THREAD

**Issue by cfHxqA** [alandoherty/protosocket-net#1]
Regards, have you a small sample how to use RequestAsync with ICorrelatableFrame in client and server?!

Server sends RequestAsync and wait for Packet (from client)
Client sends RequestAsync and wait for Packet (from server)

**Comment by alandoherty** [comment]
I've added a correlation example to README.md, hopefully that should explain correlation in ProtoSocket. The API still needs to be cleaned up, as `HasCorrelation` is mostly useless when `ShouldCorrelate` is present. It won't change until a major revision however and is used in production code without issues.

The example provided is for a request/reply exclusive protocol, you can return false in `ShouldCorrelate` when frames are not request/replies. I also implemented the interface explicitly, which is recommended but not required.

Feel free to re-open and reach out if you have any more questions.
